/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\final.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/final.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={4.702}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_6.geometry} material={materials['Environment.003']} />
          <mesh geometry={nodes.Object_6001.geometry} material={materials['Environment.003']} />
          <mesh geometry={nodes.Object_6002.geometry} material={materials['Environment.003']} position={[-20.035, 0, 0]} />
          <mesh geometry={nodes.Object_6003.geometry} material={materials['Environment.003']} position={[-20.035, 0, -8.792]} />
          <mesh geometry={nodes.Object_6004.geometry} material={materials['Environment.003']} position={[-20.035, 0, -17.596]} />
          <mesh geometry={nodes.Object_6005.geometry} material={materials['Environment.003']} position={[-20.035, 0, -25.968]} />
          <mesh geometry={nodes.Object_6006.geometry} material={materials['Environment.003']} position={[-0.028, -0.304, -25.968]} />
          <mesh geometry={nodes.Object_6007.geometry} material={materials['Environment.003']} position={[19.78, 0, 0]} />
          <mesh geometry={nodes.Object_6008.geometry} material={materials['Environment.003']} position={[19.78, 0, -8.792]} />
          <mesh geometry={nodes.Object_6009.geometry} material={materials['Environment.003']} position={[19.78, 0, -17.596]} />
          <mesh geometry={nodes.Object_6010.geometry} material={materials['Environment.003']} position={[19.78, 0, -25.968]} />
          <mesh geometry={nodes.Object_6011.geometry} material={materials['Environment.003']} position={[-20.035, 0, -33.415]} />
          <mesh geometry={nodes.Object_6012.geometry} material={materials['Environment.003']} position={[-0.028, -0.304, -33.415]} />
          <mesh geometry={nodes.Object_6013.geometry} material={materials['Environment.003']} position={[19.78, 0, -33.415]} />
          <mesh geometry={nodes.Object_4.geometry} material={materials['Props.003']} />
        </group>
      </group>
      <group position={[15.047, 40.033, -15.619]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.027}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={100}>
            <mesh geometry={nodes.Cylinder001_cables_0.geometry} material={materials['cables.001']} />
            <mesh geometry={nodes.Cylinder001_cover_0.geometry} material={materials['cover.001']} />
            <mesh geometry={nodes.Cylinder001_supports_0.geometry} material={materials['supports.001']} />
            <mesh geometry={nodes.Cylinder001_wall_mount_0.geometry} material={materials['wall_mount.001']} />
          </group>
        </group>
      </group>
      <group position={[6.213, 9.824, 14.373]} rotation={[-Math.PI / 2, 0, 0]} scale={5.843}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_5.geometry} material={materials['Lamp-light']} scale={0.41} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.Rubber} scale={0.41} />
          <mesh geometry={nodes.Object_9.geometry} material={materials.Metal} scale={0.41} />
          <mesh geometry={nodes.Object_11.geometry} material={materials['Base-plast']} scale={0.41} />
          <mesh geometry={nodes.Object_13.geometry} material={materials['Base-glossy']} scale={0.41} />
        </group>
      </group>
      <group position={[6.213, 9.824, -3.275]} rotation={[-Math.PI / 2, 0, 0]} scale={5.843}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_5001.geometry} material={materials['Lamp-light']} scale={0.41} />
          <mesh geometry={nodes.Object_7001.geometry} material={materials.Rubber} scale={0.41} />
          <mesh geometry={nodes.Object_9001.geometry} material={materials.Metal} scale={0.41} />
          <mesh geometry={nodes.Object_11001.geometry} material={materials['Base-plast']} scale={0.41} />
          <mesh geometry={nodes.Object_13001.geometry} material={materials['Base-glossy']} scale={0.41} />
        </group>
      </group>
      <mesh geometry={nodes.Text.geometry} material={materials['Material.002']} position={[11.009, 29.902, 18.895]} rotation={[Math.PI, 0, Math.PI / 2]} scale={2.19} />
      <mesh geometry={nodes.Text001.geometry} material={materials['Material.003']} position={[12.473, 38.393, -45.551]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={7.882} />
      <mesh geometry={nodes.Object_4001.geometry} material={materials['Props.002']} position={[42.245, -7.434, -19.058]} scale={5.48} />
      <mesh geometry={nodes.Plane.geometry} material={materials.grass} position={[-27.34, 8.88, 66.837]} scale={19.538} />
      <mesh geometry={nodes.Plane001.geometry} material={materials.grass} position={[-121.554, 8.88, 66.837]} scale={19.538} />
      <mesh geometry={nodes.Plane002.geometry} material={materials.grass} position={[-121.554, 8.88, 25.492]} scale={19.538} />
      <mesh geometry={nodes.Plane003.geometry} material={materials.grass} position={[-121.554, 8.88, -15.907]} scale={19.538} />
      <mesh geometry={nodes.Plane004.geometry} material={materials.grass} position={[-121.554, 8.88, -55.276]} scale={19.538} />
      <mesh geometry={nodes.Plane005.geometry} material={materials.grass} position={[-28.48, 8.88, -59.434]} scale={[19.538, 19.538, 15]} />
      <mesh geometry={nodes.Plane006.geometry} material={materials.grass} position={[65.674, 8.88, 66.837]} scale={19.538} />
      <mesh geometry={nodes.Plane007.geometry} material={materials.grass} position={[65.674, 8.88, 25.492]} scale={19.538} />
      <mesh geometry={nodes.Plane008.geometry} material={materials.grass} position={[65.674, 8.88, -15.907]} scale={19.538} />
      <mesh geometry={nodes.Plane009.geometry} material={materials.grass} position={[65.674, 8.88, -55.276]} scale={19.538} />
      <mesh geometry={nodes.Plane010.geometry} material={materials.grass} position={[-121.554, 8.88, -90.298]} scale={19.538} />
      <mesh geometry={nodes.Plane011.geometry} material={materials.grass} position={[-28.48, 8.88, -92.259]} scale={[19.538, 19.538, 18]} />
      <mesh geometry={nodes.Plane012.geometry} material={materials.grass} position={[65.674, 8.88, -90.298]} scale={19.538} />
    </group>
  )
}

useGLTF.preload('/final.glb')
